export const sentences = [
    'The quick brown fox jumps over the lazy dog, while the agile cat watches from a nearby tree, ready to pounce at any moment.',
    'A journey of a thousand miles begins with a single step, but it takes dedication and perseverance to reach the final destination.',
    'Pack my box with five dozen liquor jugs, then carefully transport them to the old warehouse on the outskirts of town.',
    'How vexingly quick daft zebras jump over the tranquil pond, startling the sleeping crocodiles and causing a commotion!',
    'Sphinx of black quartz, judge my vow of silence as I contemplate the mysteries of the ancient world and seek enlightenment.',
    'The five boxing wizards jump quickly over the lazy river, their magical powers allowing them to defy gravity with ease.',
    'Jackdaws love my big sphinx of quartz, often perching on its head to survey the surrounding desert landscape.',
    'The jay, pig, fox, zebra, and my wolves quack in unison, creating a cacophony of animal sounds that echoes through the forest.',
    'Waltz, nymph, for quick jigs vex Bud as he attempts to master the intricate dance steps at the fairy ball.',
    'Glib jocks quiz nymph to vex dwarf, their witty banter and clever wordplay leaving the small creature bewildered.',
    'Two driven jocks help fax my big quiz to the university admissions office, ensuring it arrives before the deadline.',
    'Quick zephyrs blow, vexing daft Jim as he struggles to keep his hat on during the blustery autumn day.',
    'The wizard quickly jinxed the gnomes before they vaporized, using his powerful magic to prevent their mischievous plans.',
    'A quivering Texas zombie fought republic linked jewelry thieves, protecting the valuable gems with undead determination.',
    'Crazy Fredrick bought many very exquisite opal jewels, spending his entire inheritance on the dazzling collection.',
];
