name: Deploy Angular App to GitHub Pages

on:
    push:
        branches: ['main']

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js and npm
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - name: Install dependencies
              run: npm ci

            - name: Build Angular app
              run: npm run build -- --configuration production

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Deploy to GitHub Pages
              run: npx angular-cli-ghpages --dir=dist/typing-practice
